import React, { useMemo, useState } from 'react';
import { downloadDoctorSummaryPdfWithPuppeteer } from '../../utils/generateDoctorSummaryPdf';
import type { PatientSummaryData } from '../../utils/generateDoctorSummaryPdf';

export interface DoctorSummaryPayload {
  consultation: any;
  prescriptions: any[];
  prescriptionVersions: any[];
  labReports: any[];
  priorConsultations: any[];
}

interface Props {
  payload: DoctorSummaryPayload;
  onClose: () => void;
  onRefresh: () => Promise<void>;
}

const dateText = (value?: string | Date) => value ? new Date(value).toLocaleDateString('en-GB') : 'Not recorded';
const ageText = (dob?: string) => {
  if (!dob) return 'Not recorded';
  const years = Math.max(0, Math.floor((Date.now() - new Date(dob).getTime()) / 31557600000));
  return `${years} years`;
};

const toReportData = (payload: DoctorSummaryPayload): PatientSummaryData => {
  const c = payload.consultation;
  const p = c.patientId || {};
  const labsByName = new Map<string, any[]>();
  payload.labReports.forEach((lab) => {
    const rows = labsByName.get(lab.testName) || [];
    rows.push(lab);
    labsByName.set(lab.testName, rows);
  });
  const vitalsAndLabs = Array.from(labsByName.entries()).map(([param, rows]) => ({
    param: param.toUpperCase(),
    initial: { date: dateText(rows[rows.length - 1].createdAt), value: rows[rows.length - 1].aiSummary || rows[rows.length - 1].rawText },
    lastThree: rows.slice(0, 3).map((row) => ({ date: dateText(row.createdAt), value: row.aiSummary || row.rawText })),
  }));
  const notes = [
    `Chief complaint: ${c.soapNotes?.subjective || c.symptoms?.join(', ') || 'Not recorded'}`,
    `Triage: ${c.priority?.toUpperCase() || 'GREEN'}${c.triageNotes ? ` - ${c.triageNotes}` : ''}`,
    c.soapNotes?.assessment || 'AI clinical assessment pending physician review.',
    'Draft summary generated by MediKiosk Intake Engine. Requires treating physician sign-off.',
  ];
  return {
    patientName: `${p.firstName || 'Walk-in'} ${p.lastName || 'Patient'}`,
    age: ageText(p.dateOfBirth), gender: p.gender || 'Not recorded', ampathId: p.hospitalId || 'WALK-IN',
    careSite: 'HospitalOS OPD', maritalStatus: 'Not recorded', benefitCategory: 'Not recorded', numChildren: 0,
    initialVisitDate: dateText(p.createdAt), summaryDate: dateText(c.createdAt),
    medicalHistory: (p.medicalHistory || []).map((condition: string) => ({ condition, date: 'Historical' })),
    arvTreatmentBefore: 'Not recorded', initialArvRegimen: 'Not recorded', currentArvRegimen: 'Not recorded',
    antiTbDrugs: 'Not recorded', currentOiRegimen: 'Not recorded', otherDrugsLastVisit: 'Not recorded', adherence: 'Not recorded',
    vitalsAndLabs: vitalsAndLabs.length ? vitalsAndLabs : [{ param: 'KIOSK VITALS', initial: { date: dateText(c.createdAt), value: c.soapNotes?.objective || 'Not recorded' }, lastThree: [] }],
    clinicalNotes: notes,
    chiefComplaint: c.soapNotes?.subjective || c.symptoms?.join(', ') || 'Not recorded',
    allergies: p.allergies || [],
    triage: { level: c.priority === 'emergency' ? 'RED' : c.priority === 'urgent' ? 'AMBER' : 'GREEN', priority: c.priority || 'routine', reason: c.triageNotes || 'No critical flags recorded' },
    socrates: Object.entries({
      Site: c.soapNotes?.subjective?.match(/Site: ([^\n]+)/)?.[1],
      Onset: c.soapNotes?.subjective?.match(/Onset: ([^\n]+)/)?.[1],
      Character: c.soapNotes?.subjective?.match(/Character: ([^\n]+)/)?.[1],
      Radiation: c.soapNotes?.subjective?.match(/Radiation: ([^\n]+)/)?.[1],
      Timing: c.soapNotes?.subjective?.match(/Timing: ([^\n]+)/)?.[1],
      Severity: c.soapNotes?.subjective?.match(/Severity: ([^\n]+)/)?.[1],
    }).filter(([, value]) => value).map(([label, value]) => ({ label, value: String(value) })),
    prescriptions: payload.prescriptions,
  };
};

export const DoctorSummaryModal: React.FC<Props> = ({ payload, onClose, onRefresh }) => {
  const [editingId, setEditingId] = useState<string | null>(null);
  const [medications, setMedications] = useState('');
  const [instructions, setInstructions] = useState('');
  const [saving, setSaving] = useState(false);
  const report = useMemo(() => toReportData(payload), [payload]);
  const c = payload.consultation;
  const patient = c.patientId || {};

  const beginEdit = (prescription: any) => {
    setEditingId(prescription._id);
    setMedications((prescription.medications || []).join('\n'));
    setInstructions(prescription.instructions || '');
  };

  const savePrescription = async () => {
    if (!editingId || !medications.trim() || !instructions.trim()) return;
    setSaving(true);
    try {
      const res = await fetch(`http://localhost:5000/api/v1/doctor/prescriptions/${editingId}`, {
        method: 'PATCH', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ medications: medications.split('\n').map((item) => item.trim()).filter(Boolean), instructions, changedBy: 'Doctor', changeReason: 'Physician review edit' }),
      });
      if (!res.ok) throw new Error('Prescription update failed');
      setEditingId(null);
      await onRefresh();
    } finally { setSaving(false); }
  };

  const triageClass = c.priority === 'emergency' ? 'bg-rose-600' : c.priority === 'urgent' ? 'bg-amber-500' : 'bg-emerald-600';

  return <div className="fixed inset-0 z-50 bg-slate-950/60 p-4 md:p-8 flex items-center justify-center" role="dialog" aria-modal="true">
    <div className="bg-white w-full max-w-5xl max-h-[94vh] rounded-2xl shadow-2xl overflow-hidden flex flex-col">
      <header className="p-5 border-b border-slate-200 flex items-start justify-between gap-4">
        <div><p className="text-xs uppercase tracking-widest font-black text-slate-400">Doctor Clinical Summary</p><h2 className="text-2xl font-black text-slate-900">{patient.firstName} {patient.lastName}</h2><p className="text-xs text-slate-500">{patient.hospitalId || 'WALK-IN'} · {patient.gender || 'Patient'} · {ageText(patient.dateOfBirth)}</p></div>
        <div className="flex gap-2"><button onClick={() => downloadDoctorSummaryPdfWithPuppeteer(report)} className="px-3 py-2 rounded-lg bg-indigo-600 text-white text-xs font-bold">Generate PDF</button><button onClick={onClose} className="px-3 py-2 rounded-lg bg-slate-100 text-slate-700 text-xs font-bold">Close</button></div>
      </header>
      <main className="overflow-y-auto p-5 space-y-5">
        <section className={`${triageClass} text-white rounded-xl p-4 flex flex-wrap items-center justify-between gap-3`}><div><p className="text-xs uppercase tracking-widest font-black opacity-80">Triage priority</p><p className="text-2xl font-black">{c.priority?.toUpperCase() || 'ROUTINE'}</p></div><p className="text-sm font-semibold max-w-xl">{c.triageNotes || 'No critical flags recorded'}</p></section>
        <section className="grid md:grid-cols-2 gap-4"><Info title="Chief complaint" text={c.symptoms?.join(', ') || c.diagnosis || 'Not recorded'} /><Info title="SOCRATES / SOAP summary" text={c.soapNotes?.subjective || 'Not recorded'} /><Info title="Allergies" text={(patient.allergies || []).join(', ') || 'None recorded'} /><Info title="Medical history" text={(patient.medicalHistory || []).join(', ') || 'Not recorded'} /><Info title="Objective data" text={c.soapNotes?.objective || 'Not recorded'} /><Info title="AI assessment" text={c.soapNotes?.assessment || 'Draft assessment pending physician review'} /></section>
        <section className="border border-slate-200 rounded-xl overflow-hidden"><div className="p-4 bg-slate-50"><h3 className="font-black text-sm uppercase tracking-wider">Existing prescriptions</h3></div>{payload.prescriptions.length ? payload.prescriptions.map((rx) => <div key={rx._id} className="p-4 border-t border-slate-200 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><p className="font-bold text-sm">{(rx.medications || []).join(', ')}</p><p className="text-xs text-slate-600">{rx.instructions}</p><p className="text-[10px] uppercase font-bold text-slate-400">Version {rx.version || 1} · {rx.status}</p></div><button onClick={() => beginEdit(rx)} className="self-start px-3 py-2 rounded-lg bg-slate-900 text-white text-xs font-bold">Edit</button></div>) : <p className="p-4 text-sm text-slate-500">No existing prescriptions recorded.</p>}</section>
        {editingId && <section className="border border-indigo-200 bg-indigo-50 rounded-xl p-4 space-y-3"><h3 className="font-black text-sm">Edit prescription - a new version will be preserved</h3><textarea value={medications} onChange={(e) => setMedications(e.target.value)} rows={3} placeholder="One medication per line" className="w-full rounded-lg border border-slate-300 p-3 text-sm" /><textarea value={instructions} onChange={(e) => setInstructions(e.target.value)} rows={2} placeholder="Dose, frequency, duration, instructions" className="w-full rounded-lg border border-slate-300 p-3 text-sm" /><div className="flex justify-end gap-2"><button onClick={() => setEditingId(null)} className="px-3 py-2 text-xs font-bold">Cancel</button><button disabled={saving} onClick={savePrescription} className="px-3 py-2 rounded-lg bg-indigo-600 text-white text-xs font-bold">{saving ? 'Saving...' : 'Save new version'}</button></div></section>}
        <section className="grid md:grid-cols-2 gap-4"><Info title="Care plan" text={c.soapNotes?.plan || c.treatmentPlan || 'Physician plan required'} /><Info title="Prior visits / investigations" text={`${payload.priorConsultations.length} prior consultation(s), ${payload.labReports.length} lab record(s) available`} /></section>
        <p className="text-xs text-slate-400 italic">AI-generated content is a draft and requires treating physician review and sign-off.</p>
      </main>
    </div>
  </div>;
};

const Info = ({ title, text }: { title: string; text: string }) => <div className="border border-slate-200 rounded-xl p-4"><h3 className="text-xs uppercase tracking-wider font-black text-slate-500 mb-2">{title}</h3><p className="text-sm text-slate-800 whitespace-pre-line">{text}</p></div>;

export default DoctorSummaryModal;
