import React, { useMemo, useState } from 'react';
import { downloadDoctorSummaryPdfWithPuppeteer } from '../../utils/generateDoctorSummaryPdf';
import type { PatientSummaryData } from '../../utils/generateDoctorSummaryPdf';

export interface DoctorSummaryPayload {
  consultation: any;
  prescriptions: any[];
  prescriptionVersions: any[];
  labReports: any[];
  medicalDocuments: any[];
  priorConsultations: any[];
  timeline?: any[];
  longitudinalSummary?: string;
}

interface Props {
  payload: DoctorSummaryPayload;
  onClose: () => void;
  onRefresh: () => Promise<void>;
}

const dateText = (value?: string | Date) => value ? new Date(value).toLocaleDateString('en-GB') : 'Not recorded';
const ageText = (dob?: string) => {
  if (!dob) return 'Not recorded';
  const years = Math.max(0, Math.floor((Date.now() - new Date(dob).getTime()) / 31557600000));
  return `${years} years`;
};

const toReportData = (payload: DoctorSummaryPayload): PatientSummaryData => {
  const c = payload.consultation;
  const p = c.patientId || {};
  const labsByName = new Map<string, any[]>();
  payload.labReports.forEach((lab) => {
    const rows = labsByName.get(lab.testName) || [];
    rows.push(lab);
    labsByName.set(lab.testName, rows);
  });
  const vitalsAndLabs = Array.from(labsByName.entries()).map(([param, rows]) => ({
    param: param.toUpperCase(),
    initial: { date: dateText(rows[rows.length - 1].createdAt), value: rows[rows.length - 1].aiSummary || rows[rows.length - 1].rawText },
    lastThree: rows.slice(0, 3).map((row) => ({ date: dateText(row.createdAt), value: row.aiSummary || row.rawText })),
  }));
  const kioskVitals = c.vitals || {};
  const vitalRows = [
    kioskVitals.temperature !== undefined ? { param: 'TEMPERATURE', initial: { date: dateText(c.createdAt), value: `${kioskVitals.temperature} °F` }, lastThree: [] } : null,
    ...payload.medicalDocuments.flatMap((doc) => {
      const vitals = doc.extractedVitals || {};
      const date = dateText(vitals.recordedAt || doc.createdAt);
      return [
        vitals.bloodPressure ? { param: 'HISTORICAL BLOOD PRESSURE', initial: { date, value: vitals.bloodPressure }, lastThree: [] } : null,
        vitals.bloodSugar ? { param: 'HISTORICAL BLOOD SUGAR', initial: { date, value: vitals.bloodSugar }, lastThree: [] } : null,
        vitals.spo2 ? { param: 'HISTORICAL SPO2', initial: { date, value: vitals.spo2 }, lastThree: [] } : null,
        vitals.pulse ? { param: 'HISTORICAL PULSE', initial: { date, value: vitals.pulse }, lastThree: [] } : null,
      ];
    }),
  ].filter((row): row is NonNullable<typeof row> => Boolean(row));
  const subjective = c.soapNotes?.subjective || '';
  const structuredSocrates = c.socrates && Object.keys(c.socrates).length > 0 ? c.socrates : {
    site: subjective.match(/Site: ([^\n]+)/)?.[1],
    onset: subjective.match(/Onset: ([^\n]+)/)?.[1],
    character: subjective.match(/Character: ([^\n]+)/)?.[1],
    radiation: subjective.match(/Radiation: ([^\n]+)/)?.[1],
    timing: subjective.match(/Timing: ([^\n]+)/)?.[1],
    severity: subjective.match(/Severity: ([^\n]+)/)?.[1],
  };
  const notes = [
    `Chief complaint: ${c.chiefComplaint || c.symptoms?.join(', ') || 'Not recorded'}`,
    `SOCRATES: ${Object.entries(structuredSocrates).filter(([, value]) => value).map(([key, value]) => `${key}: ${value}`).join('; ') || 'Not recorded'}`,
    `Allergies: ${(p.allergies || []).join(', ') || 'None recorded'}`,
    `Triage: ${c.priority?.toUpperCase() || 'GREEN'}${c.triageNotes ? ` - ${c.triageNotes}` : ''}`,
    `Draft digital triage (physician review required): score ${c.triageScore ?? 0}/100; reason: ${c.triageNotes || 'No urgent indicators detected'}`,
    c.historyMode === 'ayush' ? `AYUSH history: ${Object.entries(c.ayushHistory || {}).map(([key, value]) => `${key}: ${value}`).join('; ') || 'Not recorded'}` : '',
    c.soapNotes?.assessment || 'AI clinical assessment pending physician review.',
    ...payload.medicalDocuments.map((doc) => `OCR ${doc.documentType} (${doc.status === 'reviewed' ? `reviewed${doc.reviewedBy ? ` by ${doc.reviewedBy}` : ''}` : 'draft; physician review required'}): ${doc.summary || 'Draft extraction completed'}${doc.extractedMedications?.length ? ` Medicines: ${doc.extractedMedications.map((m: any) => `${m.name} ${m.dosage || ''}`).join(', ')}` : ''}`),
    ...payload.medicalDocuments.flatMap((doc) => doc.abnormalLabFlags || []),
    'Draft summary generated by MediKiosk Intake Engine. Requires treating physician sign-off.',
  ];
  const prescriptionSummary = payload.prescriptions.length
    ? payload.prescriptions.map((p) => `${(p.medications || []).join(', ')} - ${p.instructions} (v${p.version || 1}, ${p.status})`).join('; ')
    : 'None recorded';
  return {
    patientName: `${p.firstName || 'Walk-in'} ${p.lastName || 'Patient'}`,
    age: ageText(p.dateOfBirth), gender: p.gender || 'Not recorded', ampathId: p.hospitalId || 'WALK-IN',
    careSite: 'HospitalOS OPD', maritalStatus: 'Not recorded', benefitCategory: 'Not recorded', numChildren: 0,
    initialVisitDate: dateText(p.createdAt), summaryDate: dateText(c.createdAt),
    medicalHistory: [
      ...(p.medicalHistory || []).map((condition: string) => ({ condition, date: 'Historical' })),
      { condition: `CURRENT: ${c.chiefComplaint || c.symptoms?.join(', ') || 'General OPD'}`, date: dateText(c.createdAt) },
    ],
    arvTreatmentBefore: 'Not recorded', initialArvRegimen: 'Not recorded', currentArvRegimen: prescriptionSummary,
    antiTbDrugs: 'Not recorded', currentOiRegimen: 'Not recorded', otherDrugsLastVisit: 'Not recorded', adherence: 'Not recorded',
    vitalsAndLabs: [...vitalRows, ...vitalsAndLabs].length ? [...vitalRows, ...vitalsAndLabs] : [{ param: 'KIOSK VITALS', initial: { date: dateText(c.createdAt), value: c.soapNotes?.objective || 'Not recorded' }, lastThree: [] }],
    clinicalNotes: [
      ...notes,
      c.triageScore !== undefined ? `Triage score: ${c.triageScore}/100.` : '',
      c.historyMode === 'ayush' ? `AYUSH history: ${Object.entries(c.ayushHistory || {}).map(([key, value]) => `${key}: ${value}`).join('; ') || 'Not recorded'}` : '',
      payload.longitudinalSummary ? `Longitudinal summary: ${payload.longitudinalSummary}` : '',
      ...(payload.timeline || []).slice(0, 8).map((event) => `Timeline ${dateText(event.date)} [${event.type}]: ${event.title}. ${event.details || ''}`),
    ].filter(Boolean),
    chiefComplaint: c.chiefComplaint || c.symptoms?.join(', ') || 'Not recorded',
    allergies: p.allergies || [],
    triage: { level: c.priority === 'emergency' ? 'RED' : c.priority === 'urgent' ? 'AMBER' : 'GREEN', priority: c.priority || 'routine', reason: c.triageNotes || 'No critical flags recorded' },
    socrates: Object.entries(structuredSocrates).filter(([, value]) => value).map(([label, value]) => ({ label, value: String(value) })),
    prescriptions: payload.prescriptions,
    ocrDocuments: payload.medicalDocuments,
    longitudinalSummary: payload.longitudinalSummary,
    timeline: payload.timeline,
  };
};

export const DoctorSummaryModal: React.FC<Props> = ({ payload, onClose, onRefresh }) => {
  const [editingId, setEditingId] = useState<string | null>(null);
  const [medications, setMedications] = useState('');
  const [instructions, setInstructions] = useState('');
  const [saving, setSaving] = useState(false);
  const [prechecking, setPrechecking] = useState(false);
  const [safetyWarnings, setSafetyWarnings] = useState<string[]>([]);
  const [safetyChecked, setSafetyChecked] = useState(false);
  const [overrideReason, setOverrideReason] = useState('');
  const [editingDocumentId, setEditingDocumentId] = useState<string | null>(null);
  const [documentDraft, setDocumentDraft] = useState({ diagnosis: '', medications: '', labs: '', flags: '', summary: '', temperature: '', bloodPressure: '', bloodSugar: '', spo2: '', pulse: '', recordedAt: '', reviewNotes: '' });
  const [savingDocument, setSavingDocument] = useState(false);
  const [documentError, setDocumentError] = useState('');
  const report = useMemo(() => toReportData(payload), [payload]);
  const c = payload.consultation;
  const patient = c.patientId || {};

  const beginEditDocument = (document: any) => {
    const extractedVitals = document.extractedVitals || {};
    setEditingDocumentId(document._id);
    setDocumentError('');
    setDocumentDraft({
      diagnosis: document.extractedDiagnosis || '',
      medications: (document.extractedMedications || []).map((item: any) => `${item.name}${item.dosage ? ` | ${item.dosage}` : ''}`).join('\n'),
      labs: JSON.stringify(document.extractedLabValues || [], null, 2),
      flags: (document.abnormalLabFlags || []).join('\n'),
      summary: document.summary || '',
      temperature: extractedVitals.temperature || '', bloodPressure: extractedVitals.bloodPressure || '',
      bloodSugar: extractedVitals.bloodSugar || '', spo2: extractedVitals.spo2 || '', pulse: extractedVitals.pulse || '',
      recordedAt: extractedVitals.recordedAt || '', reviewNotes: document.reviewNotes || '',
    });
  };

  const saveDocumentReview = async () => {
    if (!editingDocumentId) return;
    setSavingDocument(true); setDocumentError('');
    try {
      let labs: any[] = [];
      try { labs = documentDraft.labs.trim() ? JSON.parse(documentDraft.labs) : []; } catch { throw new Error('Lab values must be valid JSON.'); }
      if (!Array.isArray(labs)) throw new Error('Lab values must be a JSON array.');
      const medications = documentDraft.medications.split('\n').map((line) => line.trim()).filter(Boolean).map((line) => {
        const [name, dosage] = line.split('|').map((part) => part.trim());
        return { name, ...(dosage ? { dosage } : {}) };
      });
      const res = await fetch(`http://localhost:5000/api/v1/doctor/documents/${editingDocumentId}/review`, {
        method: 'PATCH', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ extractedDiagnosis: documentDraft.diagnosis, extractedMedications: medications, extractedLabValues: labs, abnormalLabFlags: documentDraft.flags.split('\n').map((line) => line.trim()).filter(Boolean), summary: documentDraft.summary, extractedVitals: { temperature: documentDraft.temperature || undefined, bloodPressure: documentDraft.bloodPressure || undefined, bloodSugar: documentDraft.bloodSugar || undefined, spo2: documentDraft.spo2 || undefined, pulse: documentDraft.pulse || undefined, recordedAt: documentDraft.recordedAt || undefined }, reviewNotes: documentDraft.reviewNotes || undefined, reviewedBy: 'Doctor' }),
      });
      const data = await res.json();
      if (!res.ok || !data.success) throw new Error(data.error || 'Document review failed');
      setEditingDocumentId(null);
      await onRefresh();
    } catch (error: any) { setDocumentError(error.message || 'Document review failed'); }
    finally { setSavingDocument(false); }
  };

  const beginEdit = (prescription: any) => {
    setEditingId(prescription._id);
    setMedications((prescription.medications || []).join('\n'));
    setInstructions(prescription.instructions || '');
    setSafetyWarnings([]);
    setSafetyChecked(false);
    setOverrideReason('');
  };

  const medicationList = () => medications.split('\n').map((item) => item.trim()).filter(Boolean);

  const runSafetyCheck = async () => {
    if (!editingId || !patient._id || !medications.trim()) return false;
    setPrechecking(true);
    try {
      const res = await fetch('http://localhost:5000/api/v1/doctor/prescriptions/precheck', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ patientId: patient._id, prescriptionId: editingId, medications: medicationList() }),
      });
      if (!res.ok) throw new Error('Medication safety check failed');
      const data = await res.json();
      const warnings = data.data?.warnings || [];
      setSafetyWarnings(warnings);
      setSafetyChecked(true);
      return warnings.length === 0;
    } catch (error: any) {
      setSafetyWarnings([`${error.message || 'Medication safety check failed'}. Review manually before saving.`]);
      setSafetyChecked(false);
      return false;
    } finally { setPrechecking(false); }
  };

  const savePrescription = async (override = false) => {
    if (!editingId || !medications.trim() || !instructions.trim()) return;
    if (!override && !safetyChecked) {
      const safe = await runSafetyCheck();
      if (!safe) return;
    }
    if (override && !overrideReason.trim()) return;
    setSaving(true);
    try {
      const res = await fetch(`http://localhost:5000/api/v1/doctor/prescriptions/${editingId}`, {
        method: 'PATCH', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ medications: medicationList(), instructions, changedBy: 'Doctor', changeReason: override ? overrideReason.trim() : 'Medication safety check passed' }),
      });
      if (!res.ok) throw new Error('Prescription update failed');
      setEditingId(null);
      setSafetyWarnings([]);
      setSafetyChecked(false);
      setOverrideReason('');
      await onRefresh();
    } finally { setSaving(false); }
  };

  const triageClass = c.priority === 'emergency' ? 'bg-rose-600' : c.priority === 'urgent' ? 'bg-amber-500' : 'bg-emerald-600';

  return <div className="fixed inset-0 z-50 bg-slate-950/60 p-4 md:p-8 flex items-center justify-center" role="dialog" aria-modal="true">
    <div className="bg-white w-full max-w-5xl max-h-[94vh] rounded-2xl shadow-2xl overflow-hidden flex flex-col">
      <header className="p-5 border-b border-slate-200 flex items-start justify-between gap-4">
        <div><p className="text-xs uppercase tracking-widest font-black text-slate-400">Doctor Clinical Summary</p><h2 className="text-2xl font-black text-slate-900">{patient.firstName} {patient.lastName}</h2><p className="text-xs text-slate-500">{patient.hospitalId || 'WALK-IN'} · {patient.gender || 'Patient'} · {ageText(patient.dateOfBirth)}</p></div>
        <div className="flex gap-2"><button onClick={() => downloadDoctorSummaryPdfWithPuppeteer(report)} className="px-3 py-2 rounded-lg bg-indigo-600 text-white text-xs font-bold">Generate PDF</button><button onClick={onClose} className="px-3 py-2 rounded-lg bg-slate-100 text-slate-700 text-xs font-bold">Close</button></div>
      </header>
      <main className="overflow-y-auto p-5 space-y-5">
        <section className={`${triageClass} text-white rounded-xl p-4 flex flex-wrap items-center justify-between gap-3`}><div><p className="text-xs uppercase tracking-widest font-black opacity-80">Triage priority</p><p className="text-2xl font-black">{c.priority?.toUpperCase() || 'ROUTINE'}</p></div><p className="text-sm font-semibold max-w-xl">{c.triageNotes || 'No critical flags recorded'}</p></section>
        <section className="grid md:grid-cols-2 gap-4"><Info title="Chief complaint" text={c.symptoms?.join(', ') || c.diagnosis || 'Not recorded'} /><Info title="SOCRATES / SOAP summary" text={c.soapNotes?.subjective || 'Not recorded'} /><Info title="Allergies" text={(patient.allergies || []).join(', ') || 'None recorded'} /><Info title="Medical history" text={(patient.medicalHistory || []).join(', ') || 'Not recorded'} /><Info title="Objective data" text={c.soapNotes?.objective || 'Not recorded'} /><Info title="AI assessment" text={c.soapNotes?.assessment || 'Draft assessment pending physician review'} /></section>
        {c.historyMode === 'ayush' && <Info title="AYUSH history" text={Object.entries(c.ayushHistory || {}).map(([key, value]) => `${key}: ${value}`).join('\n') || 'Not recorded'} />}
        <section className="border border-slate-200 rounded-xl overflow-hidden"><div className="p-4 bg-slate-50"><h3 className="font-black text-sm uppercase tracking-wider">Existing prescriptions</h3></div>{payload.prescriptions.length ? payload.prescriptions.map((rx) => <div key={rx._id} className="p-4 border-t border-slate-200 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><p className="font-bold text-sm">{(rx.medications || []).join(', ')}</p><p className="text-xs text-slate-600">{rx.instructions}</p><p className="text-[10px] uppercase font-bold text-slate-400">Version {rx.version || 1} · {rx.status}</p></div><button onClick={() => beginEdit(rx)} className="self-start px-3 py-2 rounded-lg bg-slate-900 text-white text-xs font-bold">Edit</button></div>) : <p className="p-4 text-sm text-slate-500">No existing prescriptions recorded.</p>}</section>
        <section className="border border-slate-200 rounded-xl overflow-hidden"><div className="p-4 bg-slate-50"><h3 className="font-black text-sm uppercase tracking-wider">Scanned records (OCR review)</h3></div>{payload.medicalDocuments.length ? payload.medicalDocuments.map((doc) => { const v = doc.extractedVitals || {}; return <div key={doc._id} className="p-4 border-t border-slate-200 space-y-1"><div className="flex flex-wrap justify-between gap-3"><p className="font-bold text-sm">{doc.documentType}: {doc.fileName}</p><span className={`text-[10px] uppercase font-bold ${doc.status === 'reviewed' ? 'text-emerald-700' : 'text-indigo-600'}`}>{doc.status === 'reviewed' ? `Reviewed${doc.reviewedBy ? ` by ${doc.reviewedBy}` : ''}` : 'Draft'}</span></div><p className="text-xs text-slate-600">{doc.summary || 'Extraction completed; physician review required.'}</p>{doc.extractedDiagnosis && <p className="text-xs"><b>Diagnosis:</b> {doc.extractedDiagnosis}</p>}{doc.extractedMedications?.length > 0 && <p className="text-xs"><b>Medicines:</b> {doc.extractedMedications.map((m: any) => `${m.name}${m.dosage ? ` (${m.dosage})` : ''}`).join(', ')}</p>}{doc.extractedLabValues?.length > 0 && <p className="text-xs"><b>Labs:</b> {doc.extractedLabValues.map((lab: any) => `${lab.test}: ${lab.result}${lab.unit ? ` ${lab.unit}` : ''}`).join('; ')}</p>}{doc.abnormalLabFlags?.length > 0 && <p className="text-xs text-rose-700"><b>Warnings:</b> {doc.abnormalLabFlags.join('; ')}</p>}{(v.bloodPressure || v.bloodSugar || v.spo2 || v.pulse) && <p className="text-xs text-slate-600"><b>Historical OCR vitals:</b> {[v.bloodPressure && `BP ${v.bloodPressure}`, v.bloodSugar && `Sugar ${v.bloodSugar}`, v.spo2 && `SpO2 ${v.spo2}`, v.pulse && `Pulse ${v.pulse}`].filter(Boolean).join(' · ')}{v.recordedAt ? ` · ${v.recordedAt}` : ''}</p>}<button onClick={() => beginEditDocument(doc)} className="mt-2 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">{doc.status === 'reviewed' ? 'Edit review' : 'Review & edit'}</button></div>; }) : <p className="p-4 text-sm text-slate-500">No scanned records uploaded.</p>}</section>
        {editingDocumentId && <section className="border border-emerald-200 bg-emerald-50 rounded-xl p-4 space-y-3"><h3 className="font-black text-sm">Review OCR document</h3><input value={documentDraft.diagnosis} onChange={(e) => setDocumentDraft({ ...documentDraft, diagnosis: e.target.value })} placeholder="Diagnosis" className="w-full rounded-lg border border-slate-300 bg-white p-2 text-xs" /><textarea value={documentDraft.medications} onChange={(e) => setDocumentDraft({ ...documentDraft, medications: e.target.value })} rows={3} placeholder="One medicine per line: Name | dosage" className="w-full rounded-lg border border-slate-300 bg-white p-2 text-xs" /><textarea value={documentDraft.labs} onChange={(e) => setDocumentDraft({ ...documentDraft, labs: e.target.value })} rows={5} placeholder='Lab values as JSON array, e.g. [{"test":"HbA1c","result":"8.2","unit":"%","isAbnormal":true}]' className="w-full rounded-lg border border-slate-300 bg-white p-2 text-xs font-mono" /><textarea value={documentDraft.flags} onChange={(e) => setDocumentDraft({ ...documentDraft, flags: e.target.value })} rows={2} placeholder="One abnormal flag per line" className="w-full rounded-lg border border-slate-300 bg-white p-2 text-xs" /><textarea value={documentDraft.summary} onChange={(e) => setDocumentDraft({ ...documentDraft, summary: e.target.value })} rows={3} placeholder="Clinical summary" className="w-full rounded-lg border border-slate-300 bg-white p-2 text-xs" /><div className="grid grid-cols-2 md:grid-cols-3 gap-2">{(['temperature', 'bloodPressure', 'bloodSugar', 'spo2', 'pulse', 'recordedAt'] as const).map((key) => <input key={key} value={documentDraft[key]} onChange={(e) => setDocumentDraft({ ...documentDraft, [key]: e.target.value })} placeholder={`${key} (historical)`} className="rounded-lg border border-slate-300 bg-white p-2 text-xs" />)}</div><textarea value={documentDraft.reviewNotes} onChange={(e) => setDocumentDraft({ ...documentDraft, reviewNotes: e.target.value })} rows={2} placeholder="Physician review notes" className="w-full rounded-lg border border-slate-300 bg-white p-2 text-xs" />{documentError && <p className="text-xs font-bold text-rose-700">{documentError}</p>}<div className="flex justify-end gap-2"><button onClick={() => setEditingDocumentId(null)} className="px-3 py-2 text-xs font-bold">Cancel</button><button disabled={savingDocument} onClick={saveDocumentReview} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white">{savingDocument ? 'Saving...' : 'Save as reviewed'}</button></div></section>}
        {editingId && <section className="border border-indigo-200 bg-indigo-50 rounded-xl p-4 space-y-3"><h3 className="font-black text-sm">Edit prescription - a new version will be preserved</h3><textarea value={medications} onChange={(e) => { setMedications(e.target.value); setSafetyChecked(false); setSafetyWarnings([]); setOverrideReason(''); }} rows={3} placeholder="One medication per line" className="w-full rounded-lg border border-slate-300 p-3 text-sm" /><textarea value={instructions} onChange={(e) => setInstructions(e.target.value)} rows={2} placeholder="Dose, frequency, duration, instructions" className="w-full rounded-lg border border-slate-300 p-3 text-sm" />{safetyWarnings.length > 0 && <div className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-xs text-rose-900"><p className="font-black uppercase tracking-wide">Medication safety warning</p><ul className="mt-1 list-disc pl-4">{safetyWarnings.map((warning, index) => <li key={`${warning}-${index}`}>{warning}</li>)}</ul><textarea value={overrideReason} onChange={(e) => setOverrideReason(e.target.value)} rows={2} placeholder="Required to override: explain why this prescription is clinically appropriate" className="mt-3 w-full rounded-lg border border-rose-300 bg-white p-2 text-xs" /></div>}<div className="flex justify-end gap-2"><button onClick={() => setEditingId(null)} className="px-3 py-2 text-xs font-bold">Cancel</button>{safetyWarnings.length > 0 ? <button disabled={saving || !overrideReason.trim()} onClick={() => savePrescription(true)} className="px-3 py-2 rounded-lg bg-rose-600 text-white text-xs font-bold">{saving ? 'Saving...' : 'Override & save version'}</button> : <button disabled={saving || prechecking} onClick={() => savePrescription()} className="px-3 py-2 rounded-lg bg-indigo-600 text-white text-xs font-bold">{prechecking ? 'Checking...' : saving ? 'Saving...' : 'Check & save version'}</button>}</div></section>}
        <section className="grid md:grid-cols-2 gap-4"><Info title="Care plan" text={c.soapNotes?.plan || c.treatmentPlan || 'Physician plan required'} /><Info title="Prior visits / investigations" text={`${payload.priorConsultations.length} prior consultation(s), ${payload.labReports.length} lab record(s) available`} /></section>
        <section className="border border-slate-200 rounded-xl overflow-hidden"><div className="p-4 bg-slate-50"><h3 className="font-black text-sm uppercase tracking-wider">Longitudinal patient history</h3><p className="text-xs text-slate-600 mt-1">{payload.longitudinalSummary || 'No longitudinal summary available.'}</p></div>{payload.timeline?.length ? <div className="divide-y divide-slate-200">{payload.timeline.map((event, index) => <div key={`${event.type}-${event.date}-${index}`} className="p-4 flex gap-3"><div className="w-2 rounded-full bg-indigo-500 shrink-0" /><div><p className="text-[10px] uppercase font-black text-slate-400">{dateText(event.date)} · {event.type}</p><p className="font-bold text-sm text-slate-900">{event.title}</p><p className="text-xs text-slate-600 mt-1">{event.details || 'No additional details recorded.'}</p></div></div>)}</div> : <p className="p-4 text-sm text-slate-500">No prior timeline events recorded.</p>}</section>
        <p className="text-xs text-slate-400 italic">AI-generated content is a draft and requires treating physician review and sign-off.</p>
      </main>
    </div>
  </div>;
};

const Info = ({ title, text }: { title: string; text: string }) => <div className="border border-slate-200 rounded-xl p-4"><h3 className="text-xs uppercase tracking-wider font-black text-slate-500 mb-2">{title}</h3><p className="text-sm text-slate-800 whitespace-pre-line">{text}</p></div>;

export default DoctorSummaryModal;
