import React, { useMemo } from 'react';
import { downloadDoctorSummaryPdfWithPuppeteer, generateSummaryHTMLString } from '../../utils/generateDoctorSummaryPdf';
import type { PatientSummaryData } from '../../utils/generateDoctorSummaryPdf';

export interface DoctorSummaryPayload {
  consultation: any;
  prescriptions: any[];
  prescriptionVersions: any[];
  labReports: any[];
  medicalDocuments: any[];
  priorConsultations: any[];
  timeline?: any[];
  longitudinalSummary?: string;
}

interface Props {
  payload: DoctorSummaryPayload;
  onClose: () => void;
  onRefresh: () => Promise<void>;
}

const dateText = (value?: string | Date) => value ? new Date(value).toLocaleDateString('en-GB') : 'Not recorded';

const ageText = (dob?: string) => {
  if (!dob) return 'Adult';
  const years = Math.max(0, Math.floor((Date.now() - new Date(dob).getTime()) / 31557600000));
  return `${years} Yrs`;
};

const toReportData = (payload: DoctorSummaryPayload): PatientSummaryData => {
  const c = payload.consultation || {};
  const p = c.patientId || {};

  const chiefComplaint = c.chiefComplaint || (c.symptoms && c.symptoms.length > 0 ? c.symptoms[0] : c.diagnosis) || 'General Consultation';
  const symptomsList = c.symptoms && c.symptoms.length > 0 ? c.symptoms.join(', ') : 'Not recorded';

  const socrates = [
    { label: 'Main concern', value: chiefComplaint },
    { label: 'Symptoms', value: symptomsList },
    { label: 'Duration', value: c.soapNotes?.subjective?.match(/Onset: ([^\n]+)/)?.[1] || '2 days' },
    { label: 'Severity', value: c.priority === 'emergency' ? 'High (Severe)' : c.priority === 'urgent' ? 'Moderate' : 'Mild' },
    { label: 'Onset', value: 'Gradual' },
  ];

  const medicalHistory = (p.medicalHistory || []).map((condition: string) => ({
    condition,
    date: 'Historical',
  }));

  const triageLevel = c.priority === 'emergency' ? 'RED' : c.priority === 'urgent' ? 'AMBER' : 'GREEN';

  const vitalsAndLabs = [
    {
      param: 'TRIAGE SCORE',
      initial: { date: dateText(c.createdAt), value: `${c.triageScore ?? 0} / 100 (${triageLevel})` },
      lastThree: [],
    },
    ...(c.soapNotes?.objective ? [{
      param: 'KIOSK VITALS',
      initial: { date: dateText(c.createdAt), value: c.soapNotes.objective },
      lastThree: [],
    }] : []),
    ...payload.labReports.map((lab: any) => ({
      param: (lab.testName || 'LAB REPORT').toUpperCase(),
      initial: { date: dateText(lab.createdAt), value: lab.aiSummary || lab.rawText || 'Completed' },
      lastThree: [],
    })),
  ];

  const clinicalNotes = [
    `Chief Complaint: ${chiefComplaint}`,
    `SOCRATES Intake: Symptoms (${symptomsList}) | Priority (${c.priority?.toUpperCase() || 'ROUTINE'}).`,
    `Known Allergies: ${(p.allergies || []).join(', ') || 'None recorded'}`,
    `Clinical Intake Notes: ${c.triageNotes || 'No urgent indicators detected'}`,
    c.soapNotes?.assessment ? `AI Clinical Assessment: ${c.soapNotes.assessment}` : '',
    c.soapNotes?.plan ? `Care Plan: ${c.soapNotes.plan}` : '',
    'Note: Draft summary generated by MediKiosk Intake Engine. Requires treating physician sign-off.',
  ].filter(Boolean);

  return {
    patientName: `${p.firstName || 'Walk-in'} ${p.lastName || 'Patient'}`,
    age: ageText(p.dateOfBirth),
    gender: p.gender || 'Not recorded',
    ampathId: p.hospitalId || 'WALK-IN',
    careSite: 'HospitalOS OPD',
    maritalStatus: 'Single',
    benefitCategory: 'OPD Intake',
    numChildren: 0,
    initialVisitDate: dateText(p.createdAt || c.createdAt),
    summaryDate: dateText(c.createdAt),
    medicalHistory,
    arvTreatmentBefore: 'N/A',
    initialArvRegimen: 'N/A',
    currentArvRegimen: payload.prescriptions?.map(p => (p.medications || []).join(', ')).join('; ') || 'None prescribed',
    antiTbDrugs: 'None',
    currentOiRegimen: 'None',
    otherDrugsLastVisit: 'None',
    adherence: 'Good',
    vitalsAndLabs,
    clinicalNotes,
    chiefComplaint,
    socrates,
    symptoms: c.symptoms,
    allergies: p.allergies,
    triage: {
      level: triageLevel,
      priority: c.priority || 'routine',
      reason: c.triageNotes || 'Standard intake',
    },
  };
};

export const DoctorSummaryModal: React.FC<Props> = ({ payload, onClose }) => {
  const report = useMemo(() => toReportData(payload), [payload]);
  const htmlContent = useMemo(() => generateSummaryHTMLString(report), [report]);

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/70 p-3 sm:p-6 flex items-center justify-center font-sans antialiased" role="dialog" aria-modal="true">
      <div className="bg-white w-full max-w-4xl max-h-[95vh] rounded-2xl shadow-2xl overflow-hidden flex flex-col border border-slate-200">
        
        {/* Header */}
        <header className="px-6 py-4 bg-white border-b border-slate-200 flex items-center justify-between gap-4">
          <div>
            <div className="flex items-center space-x-2">
              <span className="text-xs font-black uppercase tracking-widest text-slate-400">Aethera PDF Summary</span>
              <span className="px-2 py-0.5 text-[10px] font-bold bg-slate-100 text-slate-700 rounded">
                ID: {report.ampathId}
              </span>
            </div>
            <h2 className="text-lg font-black text-slate-900 tracking-tight mt-0.5">
              {report.patientName} ({report.gender}, {report.age})
            </h2>
          </div>

          <div className="flex items-center space-x-3">
            <button
              type="button"
              onClick={() => void downloadDoctorSummaryPdfWithPuppeteer(report)}
              className="px-4 py-2 bg-white hover:bg-slate-50 border border-slate-300 text-slate-900 rounded-xl text-xs font-extrabold uppercase tracking-wider flex items-center space-x-2 shadow-sm transition-all cursor-pointer"
            >
              <span>📥 Download / Print PDF</span>
            </button>
            <button
              type="button"
              onClick={onClose}
              className="px-3.5 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-bold transition-all cursor-pointer"
            >
              ✕ Close
            </button>
          </div>
        </header>

        {/* Paper Document Preview (1:1 with PDF Generator) */}
        <main className="flex-1 bg-slate-100 p-4 sm:p-6 overflow-y-auto">
          <div className="max-w-3xl mx-auto bg-white rounded-xl shadow-md border border-slate-200 overflow-hidden min-h-[750px]">
            <iframe
              title="Doctor Clinical Summary PDF Generator Preview"
              srcDoc={htmlContent}
              className="w-full h-[750px] border-none"
            />
          </div>
        </main>
      </div>
    </div>
  );
};

export default DoctorSummaryModal;
