/**
 * Doctor Clinical Summary Report PDF & Print Generator
 * Formats patient intake data into the AMPATH Guide Clinical Summary layout
 */

export interface PatientSummaryData {
  patientName: string;
  age: string;
  gender: string;
  ampathId: string;
  careSite: string;
  maritalStatus: string;
  benefitCategory: string;
  numChildren: number;
  initialVisitDate: string;
  summaryDate: string;
  medicalHistory: Array<{ condition: string; date: string }>;
  arvTreatmentBefore: string;
  initialArvRegimen: string;
  currentArvRegimen: string;
  antiTbDrugs: string;
  currentOiRegimen: string;
  otherDrugsLastVisit: string;
  adherence: string;
  vitalsAndLabs: Array<{
    param: string;
    initial: { date: string; value: string };
    lastThree: Array<{ date: string; value: string }>;
  }>;
  clinicalNotes: string[];
}

export const DEFAULT_STATIC_SUMMARY_DATA: PatientSummaryData = {
  patientName: 'Rahul Sharma',
  age: '43 Yrs 8 Months',
  gender: 'Male',
  ampathId: '00366',
  careSite: 'MTRH',
  maritalStatus: 'Married',
  benefitCategory: 'MTCT-Plus',
  numChildren: 4,
  initialVisitDate: '26/11/2002',
  summaryDate: '09/06/2004',
  medicalHistory: [
    { condition: 'DECREASING CD4 COUNT', date: '05/05/2004' },
    { condition: 'DIARRHEA', date: '26/11/2002' },
    { condition: 'HYPERACIDITY & ACUTE GASTRITIS', date: '15/09/2025' },
    { condition: 'ROTATOR CUFF TENDINITIS', date: '12/03/2026' },
  ],
  arvTreatmentBefore: 'Yes None Or Not Indicated',
  initialArvRegimen: '03/09/2003 Lamivudine Stavudine Nevirapine',
  currentArvRegimen: 'Lamivudine Stavudine Nevirapine',
  antiTbDrugs: 'None',
  currentOiRegimen: '05/05/2004 Cotrimoxazole',
  otherDrugsLastVisit: 'None',
  adherence: 'Perfect',
  vitalsAndLabs: [
    {
      param: 'WEIGHT',
      initial: { date: '26/11/2002', value: '58' },
      lastThree: [
        { date: '06/04/2004', value: '75' },
        { date: '07/04/2004', value: '75' },
        { date: '05/05/2004', value: '74' },
      ],
    },
    {
      param: 'SAO2',
      initial: { date: '26/11/2002', value: '98' },
      lastThree: [
        { date: '06/04/2004', value: '96' },
        { date: '07/04/2004', value: '95' },
        { date: '05/05/2004', value: '92' },
      ],
    },
    {
      param: 'HEMOGLOBIN',
      initial: { date: '12/09/2002', value: '12.1' },
      lastThree: [{ date: '22/05/2003', value: '12.3' }],
    },
    {
      param: 'WHITE BLOOD CELLS',
      initial: { date: '12/09/2002', value: '5700' },
      lastThree: [{ date: '22/05/2003', value: '5200' }],
    },
    {
      param: 'CD4',
      initial: { date: '12/09/2002', value: '54' },
      lastThree: [
        { date: '26/07/2003', value: '175' },
        { date: '07/04/2004', value: '170' },
      ],
    },
    {
      param: 'CHEST X-RAY',
      initial: { date: '26/11/2002', value: 'NAD' },
      lastThree: [],
    },
    {
      param: 'ALC',
      initial: { date: '12/09/2002', value: '2200' },
      lastThree: [],
    },
    {
      param: 'PLATELETS',
      initial: { date: '12/09/2002', value: '355000' },
      lastThree: [{ date: '22/05/2003', value: '353000' }],
    },
    {
      param: 'SGPT',
      initial: { date: '26/11/2002', value: '40.9' },
      lastThree: [{ date: '07/04/2004', value: '14' }],
    },
  ],
  clinicalNotes: [
    'Patient reported chief complaint of acute gastric discomfort and right shoulder muscle strain during MediKiosk intake.',
    'Vital signs within normal limits (SaO2: 98%, Pulse: 72 bpm). No active red flag chest pain symptoms detected.',
    'Medication Adherence noted as Perfect on previous visit. Continue Cotrimoxazole & ARV regimen as prescribed.',
    'Note: Draft summary generated by MediKiosk Intake Engine. Requires treating physician sign-off.',
  ],
};

/**
 * Generates exact printable HTML matching the AMPATH Guide Adult Summary layout
 */
export const generateSummaryHTMLString = (data: PatientSummaryData = DEFAULT_STATIC_SUMMARY_DATA): string => {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>AMPATH Guide Adult Summary - ${data.patientName}</title>
  <style>
    @page { size: A4 portrait; margin: 12mm 15mm 12mm 15mm; }
    body { font-family: Arial, Helvetica, sans-serif; font-size: 11px; color: #000; background: #fff; margin: 0; padding: 20px; line-height: 1.3; }
    @media print { body { padding: 0; } .no-print { display: none !important; } }
    .no-print { background: #1e293b; color: #fff; padding: 12px 20px; border-radius: 8px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; }
    .no-print button { background: #2563eb; color: #fff; border: none; padding: 8px 16px; font-weight: bold; border-radius: 6px; cursor: pointer; }
    .doc-header { text-align: center; font-size: 16px; font-weight: bold; text-decoration: underline; margin-bottom: 12px; }
    .section-title { font-size: 12px; font-weight: bold; text-decoration: underline; margin-top: 14px; margin-bottom: 6px; }
    .meta-grid { display: grid; grid-template-columns: 1.5fr 1.2fr 1fr; row-gap: 4px; column-gap: 12px; margin-bottom: 10px; }
    .field-label { font-weight: bold; }
    .field-val { text-decoration: underline; font-weight: bold; }
    .history-table { width: 100%; margin-bottom: 10px; border-collapse: collapse; }
    .history-table td { padding: 2px 0; font-weight: bold; font-size: 10.5px; }
    .drug-grid { display: grid; grid-template-columns: 1fr 1fr; row-gap: 8px; column-gap: 20px; margin-bottom: 14px; }
    .drug-q { font-weight: bold; margin-bottom: 2px; }
    .drug-ans { font-weight: bold; padding-left: 20px; }
    .results-table { width: 100%; border-collapse: collapse; border: 2px solid #000; margin-top: 14px; margin-bottom: 14px; }
    .results-table th, .results-table td { border: 1px solid #000; padding: 4px 8px; text-align: center; font-size: 10px; }
    .results-table th { font-weight: bold; font-size: 11px; }
    .results-table td.param-name { text-align: left; font-weight: bold; width: 150px; }
    .reminders-box { margin-top: 12px; padding-top: 8px; border-top: 1px dashed #000; }
    .reminders-title { font-weight: bold; text-decoration: underline; margin-bottom: 4px; }
    .reminders-list { margin: 0; padding-left: 18px; font-size: 10.5px; }
    .reminders-list li { margin-bottom: 3px; }
    .doctor-signoff { margin-top: 25px; display: flex; justify-content: space-between; align-items: flex-end; font-size: 10px; font-weight: bold; }
    .sign-line { border-top: 1px solid #000; width: 200px; text-align: center; padding-top: 4px; }
  </style>
</head>
<body>
  <div class="no-print">
    <div>
      <h2 style="margin:0;font-size:14px;">Doctor Clinical Summary PDF Generator</h2>
      <span style="font-size:11px;color:#94a3b8;">AMPATH Guide Layout Format — Static Patient Intake Preview</span>
    </div>
    <button onclick="window.print()">🖨️ Save as PDF / Print</button>
  </div>

  <div class="doc-header">
    AMPATH Guide Adult Summary as of: ${data.summaryDate}
  </div>

  <div class="section-title">Personal History:</div>
  <div class="meta-grid">
    <div>
      <span class="field-label">for initial visit</span><br>
      Initial AMPATH Visit: <span class="field-val">${data.initialVisitDate}</span>
    </div>
    <div>
      Age: <span class="field-val">${data.age}</span><br>
      Benefit Category: <span class="field-val">${data.benefitCategory}</span>
    </div>
    <div>
      AMPATH ID: <span class="field-val">${data.ampathId}</span><br>
      Care Site: <span class="field-val">${data.careSite}</span><br>
      Marital Status: <span class="field-val">${data.maritalStatus}</span><br>
      Number Of Children: <span class="field-val">${data.numChildren}</span>
    </div>
  </div>

  <div class="section-title">Medical History:</div>
  <table class="history-table">
    ${data.medicalHistory
      .map(
        item => `
      <tr>
        <td style="width:250px;">${item.condition}</td>
        <td style="width:140px;">${item.date}</td>
      </tr>`
      )
      .join('')}
  </table>

  <div class="section-title">Drug History</div>
  <div class="drug-grid">
    <div>
      <div class="drug-q">ARV treatment before AMPATH?</div>
      <div class="drug-ans">${data.arvTreatmentBefore}</div>
    </div>
    <div>
      <div class="drug-q">Initial AMPATH ARV regimen?</div>
      <div class="drug-ans">${data.initialArvRegimen}</div>
    </div>

    <div>
      <div class="drug-q">Current AMPATH ARV regimen?</div>
      <div class="drug-ans">${data.currentArvRegimen}</div>
    </div>
    <div>
      <div class="drug-q">Anti TB Drugs?</div>
      <div class="drug-ans">${data.antiTbDrugs}</div>
    </div>

    <div>
      <div class="drug-q">Current AMPATH OI regimen?</div>
      <div class="drug-ans">${data.currentOiRegimen}</div>
    </div>
    <div>
      <div class="drug-q">Other drugs prescribed on last visit?</div>
      <div class="drug-ans">${data.otherDrugsLastVisit}</div>
    </div>

    <div>&nbsp;</div>
    <div>
      <div class="drug-q">Adherence Perfect [Last Visit]?: &nbsp;&nbsp;&nbsp;<u>${data.adherence}</u></div>
    </div>
  </div>

  <table class="results-table">
    <thead>
      <tr>
        <th class="param-name">&nbsp;</th>
        <th style="width:120px;">Initial Result</th>
        <th colspan="3">Last Three Results</th>
      </tr>
    </thead>
    <tbody>
      ${data.vitalsAndLabs
        .map(row => {
          const l1 = row.lastThree[0] ? `${row.lastThree[0].date}<br><b>${row.lastThree[0].value}</b>` : '-';
          const l2 = row.lastThree[1] ? `${row.lastThree[1].date}<br><b>${row.lastThree[1].value}</b>` : '-';
          const l3 = row.lastThree[2] ? `${row.lastThree[2].date}<br><b>${row.lastThree[2].value}</b>` : '-';
          return `
          <tr>
            <td class="param-name">${row.param}</td>
            <td>${row.initial.date}<br><b>${row.initial.value}</b></td>
            <td>${l1}</td>
            <td>${l2}</td>
            <td>${l3}</td>
          </tr>`;
        })
        .join('')}
    </tbody>
  </table>

  <div class="reminders-box">
    <div class="reminders-title">Clinical Reminders & AI Pre-Consultation Notes:</div>
    <ol class="reminders-list">
      ${data.clinicalNotes.map(n => `<li>${n}</li>`).join('')}
    </ol>

    <div class="doctor-signoff">
      <div>Generated: ${data.summaryDate} | System: HospitalOS MediKiosk</div>
      <div class="sign-line">Treating Physician Signature / Stamp</div>
    </div>
  </div>
</body>
</html>`;
};

/**
 * Triggers PDF print window immediately
 */
export const openDoctorSummaryPdfWindow = (data: PatientSummaryData = DEFAULT_STATIC_SUMMARY_DATA) => {
  const htmlContent = generateSummaryHTMLString(data);
  const printWindow = window.open('', '_blank', 'width=900,height=1000');
  if (printWindow) {
    printWindow.document.open();
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  } else {
    // Fallback if popup blocker is enabled: redirect to static file
    window.open('/doctor_clinical_summary.html', '_blank');
  }
};

/**
 * Opens docgenerator.html directly in a new browser window/tab
 */
export const openDocGeneratorHtmlWindow = (_data: PatientSummaryData = DEFAULT_STATIC_SUMMARY_DATA) => {
  window.open('/docgenerator.html', '_blank');
};

/**
 * Direct Client-Side PDF Download (Amira Law PDF Generator pattern)
 * Opens /docgenerator.html?autodownload=true in hidden iframe or direct popup to trigger immediate PDF export
 */
export const downloadDoctorSummaryPdfDirect = async (
  data: PatientSummaryData = DEFAULT_STATIC_SUMMARY_DATA
): Promise<void> => {
  // First try backend Puppeteer service
  try {
    const htmlContent = generateSummaryHTMLString(data);
    const res = await fetch('/api/v1/medikiosk/generate-pdf', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ htmlContent }),
    });

    if (res.ok) {
      const pdfBlob = await res.blob();
      const url = URL.createObjectURL(pdfBlob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Doctor_Clinical_Summary_${data.ampathId || '00366'}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      return;
    }
  } catch (err) {
    console.warn('Backend PDF endpoint unavailable, falling back to frontend docgenerator.html:', err);
  }

  // Frontend Fallback: Trigger direct PDF download via /docgenerator.html
  window.open('/docgenerator.html?autodownload=true', '_blank');
};

/**
 * Uses Express backend Puppeteer service or falls back to client-side docgenerator.html
 */
export const downloadDoctorSummaryPdfWithPuppeteer = downloadDoctorSummaryPdfDirect;

