/**
 * Aethera Clinical Summary PDF Generator
 * Formats patient intake data into the clean layout matching the reference Aethera design template
 */

export interface PatientSummaryData {
  patientName: string;
  age: string;
  gender: string;
  ampathId: string;
  careSite: string;
  maritalStatus: string;
  benefitCategory: string;
  numChildren: number;
  initialVisitDate: string;
  summaryDate: string;
  medicalHistory: Array<{ condition: string; date: string }>;
  arvTreatmentBefore: string;
  initialArvRegimen: string;
  currentArvRegimen: string;
  antiTbDrugs: string;
  currentOiRegimen: string;
  otherDrugsLastVisit: string;
  adherence: string;
  vitalsAndLabs: Array<{
    param: string;
    initial: { date: string; value: string };
    lastThree: Array<{ date: string; value: string }>;
  }>;
  clinicalNotes: string[];
  triage?: { level: string; priority: string; reason: string };
  chiefComplaint?: string;
  socrates?: Array<{ label: string; value: string }>;
  symptoms?: string[];
  allergies?: string[];
  prescriptions?: Array<{ medications: string[]; instructions: string; status: string; version?: number }>;
  ocrDocuments?: Array<{ fileName: string; documentType: string; summary: string; abnormalLabFlags?: string[] }>;
  longitudinalSummary?: string;
  timeline?: Array<{ date: string; type: string; title: string; details?: string }>;
}

export const DEFAULT_STATIC_SUMMARY_DATA: PatientSummaryData = {
  patientName: 'Rahul Sharma',
  age: '43 Yrs 8 Months',
  gender: 'Male',
  ampathId: '00366',
  careSite: 'MTRH',
  maritalStatus: 'Married',
  benefitCategory: 'MTCT-Plus',
  numChildren: 4,
  initialVisitDate: '26/11/2002',
  summaryDate: '09/06/2004',
  medicalHistory: [
    { condition: 'DECREASING CD4 COUNT', date: '05/05/2004' },
    { condition: 'DIARRHEA', date: '26/11/2002' },
    { condition: 'HYPERACIDITY & ACUTE GASTRITIS', date: '15/09/2025' },
    { condition: 'ROTATOR CUFF TENDINITIS', date: '12/03/2026' },
  ],
  arvTreatmentBefore: 'Yes None Or Not Indicated',
  initialArvRegimen: '03/09/2003 Lamivudine Stavudine Nevirapine',
  currentArvRegimen: 'Lamivudine, Stavudine, Nevirapine',
  antiTbDrugs: 'None',
  currentOiRegimen: 'Cotrimoxazole',
  otherDrugsLastVisit: 'None',
  adherence: 'perfect',
  vitalsAndLabs: [
    {
      param: 'WEIGHT',
      initial: { date: '26/11/2002', value: '58' },
      lastThree: [
        { date: '06/04/2004', value: '75' },
        { date: '07/04/2004', value: '75' },
        { date: '05/05/2004', value: '74' },
      ],
    },
    {
      param: 'SAO2',
      initial: { date: '26/11/2002', value: '98' },
      lastThree: [
        { date: '06/04/2004', value: '96' },
        { date: '07/04/2004', value: '95' },
        { date: '05/05/2004', value: '92' },
      ],
    },
    {
      param: 'HEMOGLOBIN',
      initial: { date: '12/09/2002', value: '12.1' },
      lastThree: [{ date: '22/05/2003', value: '12.3' }],
    },
    {
      param: 'WHITE BLOOD CELLS',
      initial: { date: '12/09/2002', value: '5700' },
      lastThree: [{ date: '22/05/2003', value: '5200' }],
    },
    {
      param: 'CD4',
      initial: { date: '12/09/2002', value: '54' },
      lastThree: [
        { date: '26/07/2003', value: '175' },
        { date: '07/04/2004', value: '170' },
      ],
    },
    {
      param: 'CHEST X-RAY',
      initial: { date: '26/11/2002', value: 'NAD' },
      lastThree: [],
    },
    {
      param: 'ALC',
      initial: { date: '12/09/2002', value: '2200' },
      lastThree: [],
    },
    {
      param: 'PLATELETS',
      initial: { date: '12/09/2002', value: '355000' },
      lastThree: [{ date: '22/05/2003', value: '353000' }],
    },
    {
      param: 'SGPT',
      initial: { date: '26/11/2002', value: '40.9' },
      lastThree: [{ date: '07/04/2004', value: '14' }],
    },
  ],
  clinicalNotes: [
    'Patient reported chief complaint of acute gastric discomfort and right shoulder muscle strain during MediKiosk intake.',
    'Vital signs within normal limits (SaO2: 98%, Pulse: 72 bpm). No active red flag chest pain symptoms detected.',
    'Medication Adherence noted as Perfect on previous visit. Continue Cotrimoxazole & ARV regimen as prescribed.',
    'Note: Draft summary generated by MediKiosk Intake Engine. Requires treating physician sign-off.',
  ],
};

const escapeHtml = (value: unknown): string => String(value ?? 'Not recorded')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#039;');

/**
 * Generates ultra-clean printable HTML matching the Aethera Clinical Summary design template
 */
export const generateSummaryHTMLString = (data: PatientSummaryData = DEFAULT_STATIC_SUMMARY_DATA): string => {
  const getSocratesVal = (key: string): string => {
    if (!data.socrates) return '';
    const item = data.socrates.find(s => s.label.toLowerCase().includes(key.toLowerCase()));
    return item ? item.value : '';
  };

  const mainConcern = escapeHtml(data.chiefComplaint || getSocratesVal('site') || 'Fever');
  const symptomsVal = escapeHtml(getSocratesVal('associated') || getSocratesVal('symptom') || (data.symptoms || []).join(' ') || 'Headache Body ache');
  const durationVal = escapeHtml(getSocratesVal('duration') || getSocratesVal('onset') || '2 days');
  const severityVal = escapeHtml(getSocratesVal('severity') || 'Moderate');
  const onsetVal = escapeHtml(getSocratesVal('onset') || getSocratesVal('character') || 'Gradual');

  const medicalHistoryRows = (data.medicalHistory && data.medicalHistory.length > 0)
    ? data.medicalHistory.map(item => `
        <div style="margin-bottom: 5px; font-weight: bold; font-size: 8.5pt; display: flex; justify-content: space-between; max-width: 440pt;">
          <span>${escapeHtml(item.condition.toUpperCase())}</span>
          <span>${escapeHtml(item.date)}</span>
        </div>
      `).join('')
    : `<div style="font-size: 8pt; font-style: italic;">NO PRIOR MEDICAL HISTORY RECORDED</div>`;

  const isRed = data.triage?.level === 'RED';
  const isAmber = data.triage?.level === 'AMBER';

  const riskRowsHtml = `
    <tr style="border-bottom: 1px solid #000000; height: 16pt;">
      <td style="width: 130pt; padding: 2px 6px; border-right: 1px solid #000000;">Chest pain</td>
      <td style="width: 150pt; padding: 2px 6px;">${isRed ? 'high' : 'normal'}</td>
    </tr>
    <tr style="border-bottom: 1px solid #000000; height: 16pt;">
      <td style="padding: 2px 6px; border-right: 1px solid #000000;">Discomfort</td>
      <td style="padding: 2px 6px;">${isAmber ? 'Moderate' : isRed ? 'high' : 'normal'}</td>
    </tr>
    <tr style="height: 16pt;">
      <td style="padding: 2px 6px; border-right: 1px solid #000000;">Shortness of breath</td>
      <td style="padding: 2px 6px;">${isRed ? 'high' : 'normal'}</td>
    </tr>
  `;

  const vitalsRows = (data.vitalsAndLabs || []).map((row, idx) => {
    const isLast = idx === (data.vitalsAndLabs.length - 1);
    const borderBottomStyle = isLast ? 'border-bottom: 1.5px solid #000000;' : 'border-bottom: 1px solid #000000;';

    const l1Date = row.lastThree?.[0]?.date || '';
    const l1Val = row.lastThree?.[0]?.value || '-';
    const l2Date = row.lastThree?.[1]?.date || '';
    const l2Val = row.lastThree?.[1]?.value || '-';
    const l3Date = row.lastThree?.[2]?.date || '';
    const l3Val = row.lastThree?.[2]?.value || '-';

    return `
      <tr style="${borderBottomStyle} height: 25pt;">
        <td style="width: 125pt; padding: 6px 8px; font-weight: bold; border-right: 1px solid #000000; font-size: 7.5pt;">${escapeHtml(row.param)}</td>
        <td style="width: 102pt; padding: 2px 4px; text-align: center; border-right: 1px solid #000000; font-size: 7.5pt;">
          <div style="font-size: 7pt; color: #000;">${escapeHtml(row.initial.date)}</div>
          <div style="font-weight: bold;">${escapeHtml(row.initial.value)}</div>
        </td>
        <td style="width: 93pt; padding: 2px 4px; text-align: center; border-right: 1px solid #000000; font-size: 7.5pt;">
          ${l1Date ? `<div style="font-size: 7pt;">${escapeHtml(l1Date)}</div>` : ''}
          <div style="font-weight: bold;">${escapeHtml(l1Val)}</div>
        </td>
        <td style="width: 93pt; padding: 2px 4px; text-align: center; border-right: 1px solid #000000; font-size: 7.5pt;">
          ${l2Date ? `<div style="font-size: 7pt;">${escapeHtml(l2Date)}</div>` : ''}
          <div style="font-weight: bold;">${escapeHtml(l2Val)}</div>
        </td>
        <td style="width: 93pt; padding: 2px 4px; text-align: center; font-size: 7.5pt;">
          ${l3Date ? `<div style="font-size: 7pt;">${escapeHtml(l3Date)}</div>` : ''}
          <div style="font-weight: bold;">${escapeHtml(l3Val)}</div>
        </td>
      </tr>
    `;
  }).join('\n');

  const notesHtml = (data.clinicalNotes || []).map(note => `
    <li style="margin-bottom: 4px; font-size: 7.5pt; color: #000000; line-height: 1.2;">${escapeHtml(note)}</li>
  `).join('\n');

  return `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Aethera Pre-Consultation Summary - ${escapeHtml(data.patientName)}</title>
    <style>
        @page { size: A4 portrait; margin: 12mm 15mm 12mm 15mm; }
        body { font-family: 'Arial', sans-serif; font-size: 8.5pt; color: #000000; background: #ffffff; margin: 0; padding: 20px; line-height: 1.2; }
        p { margin: 0; }
        h1 { margin: 0; }
        h2 { margin: 0; }
        table td { vertical-align: top; }
    </style>
</head>
<body>
    <!-- Centered Aethera Header -->
    <div style="text-align: center; margin-bottom: 16px;">
        <div style="font-family: 'Arial', sans-serif; font-size: 20pt; font-weight: 400; letter-spacing: 7px; color: #000000; text-transform: uppercase;">
            A E T H E R A
        </div>
        <div style="font-family: 'Arial', sans-serif; font-size: 7pt; color: #222222; letter-spacing: 0.5px; margin-top: 2px;">
            More time for care, zero time on paperwork.
        </div>
        <div style="width: 160px; height: 1.5px; background-color: #000000; margin: 4px auto 0 auto;"></div>
    </div>

    <!-- Document Title -->
    <h1 style="text-align: center; font-size: 12.5pt; font-weight: bold; text-decoration: underline; margin-bottom: 14px; font-family: 'Arial', sans-serif;">
        PRE- CONSULTATION PATIENT SUMMARY
    </h1>

    <!-- Personal History Section -->
    <h2 style="font-size: 9.5pt; font-weight: bold; text-decoration: underline; margin-top: 10px; margin-bottom: 4px; font-family: 'Arial', sans-serif;">
        Personal History:
    </h2>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 14px; font-size: 8.5pt; font-family: 'Arial', sans-serif;">
        <tr>
            <td style="width: 38%; vertical-align: top;">
                Name:<span style="font-weight: normal;">${escapeHtml(data.patientName)}</span><br>
                <div style="margin-top: 3px;">Initial Visit: <span style="font-weight: bold; text-decoration: underline;">${escapeHtml(data.initialVisitDate)}</span></div>
            </td>
            <td style="width: 32%; vertical-align: top; text-align: center;">
                Age: <span style="font-weight: bold; text-decoration: underline;">${escapeHtml(data.age)}</span>
            </td>
            <td style="width: 30%; vertical-align: top; text-align: right;">
                ABHA ID: <span style="font-weight: bold; text-decoration: underline;">${escapeHtml(data.ampathId)}</span><br>
                <div style="margin-top: 3px;">Marital Status: <span style="font-weight: bold; text-decoration: underline;">${escapeHtml(data.maritalStatus)}</span></div>
            </td>
        </tr>
    </table>

    <!-- Current Visit Section -->
    <h2 style="font-size: 9.5pt; font-weight: bold; text-decoration: underline; margin-top: 10px; margin-bottom: 4px; font-family: 'Arial', sans-serif;">
        Current Visit:
    </h2>
    <table style="width: 300pt; border-collapse: collapse; margin-bottom: 14px; border: 1px solid #000000; font-size: 8pt; font-family: 'Arial', sans-serif;">
        <tr style="border-bottom: 1px solid #000000; height: 16pt;">
            <td style="width: 126pt; padding: 2px 6px; font-weight: bold; border-right: 1px solid #000000;">Findings</td>
            <td style="width: 174pt; padding: 2px 6px; font-weight: bold;">Details</td>
        </tr>
        <tr style="border-bottom: 1px solid #000000; height: 16pt;">
            <td style="padding: 2px 6px; font-weight: bold; border-right: 1px solid #000000;">Main concern</td>
            <td style="padding: 2px 6px;">${mainConcern}</td>
        </tr>
        <tr style="border-bottom: 1px solid #000000; height: 16pt;">
            <td style="padding: 2px 6px; font-weight: bold; text-decoration: underline; border-right: 1px solid #000000;">Symtoms</td>
            <td style="padding: 2px 6px;">${symptomsVal}</td>
        </tr>
        <tr style="border-bottom: 1px solid #000000; height: 16pt;">
            <td style="padding: 2px 6px; font-weight: bold; border-right: 1px solid #000000;">Duration</td>
            <td style="padding: 2px 6px;">${durationVal}</td>
        </tr>
        <tr style="border-bottom: 1px solid #000000; height: 16pt;">
            <td style="padding: 2px 6px; font-weight: bold; border-right: 1px solid #000000;">Severity</td>
            <td style="padding: 2px 6px;">${severityVal}</td>
        </tr>
        <tr style="height: 16pt;">
            <td style="padding: 2px 6px; font-weight: bold; border-right: 1px solid #000000;">Onset</td>
            <td style="padding: 2px 6px;">${onsetVal}</td>
        </tr>
    </table>

    <!-- Medical History Section -->
    <h2 style="font-size: 9.5pt; font-weight: bold; text-decoration: underline; margin-top: 10px; margin-bottom: 6px; font-family: 'Arial', sans-serif;">
        Medical History:
    </h2>
    <div style="margin-bottom: 14px;">
        ${medicalHistoryRows}
    </div>

    <!-- Current Medications Section -->
    <h2 style="font-size: 9.5pt; font-weight: bold; text-decoration: underline; margin-top: 10px; margin-bottom: 4px; font-family: 'Arial', sans-serif;">
        Current Medications:
    </h2>
    <table style="width: 300pt; border-collapse: collapse; margin-bottom: 14px; border: 1px solid #000000; font-size: 8pt; font-family: 'Arial', sans-serif;">
        <tr style="border-bottom: 1px solid #000000; height: 16pt;">
            <td style="width: 126pt; padding: 2px 6px; font-weight: bold; border-right: 1px solid #000000;">Medication Information</td>
            <td style="width: 174pt; padding: 2px 6px; font-weight: bold;">Details</td>
        </tr>
        <tr style="border-bottom: 1px solid #000000; height: 16pt;">
            <td style="padding: 2px 6px; border-right: 1px solid #000000;">Current AVR</td>
            <td style="padding: 2px 6px;">${escapeHtml(data.currentArvRegimen || 'None')}</td>
        </tr>
        <tr style="border-bottom: 1px solid #000000; height: 16pt;">
            <td style="padding: 2px 6px; border-right: 1px solid #000000;">OL Treatment</td>
            <td style="padding: 2px 6px;">${escapeHtml(data.currentOiRegimen || 'None')}</td>
        </tr>
        <tr style="border-bottom: 1px solid #000000; height: 16pt;">
            <td style="padding: 2px 6px; border-right: 1px solid #000000;">Drugs</td>
            <td style="padding: 2px 6px;">${escapeHtml(data.otherDrugsLastVisit || 'None')}</td>
        </tr>
        <tr style="height: 16pt;">
            <td style="padding: 2px 6px; border-right: 1px solid #000000;">Last visit adherence</td>
            <td style="padding: 2px 6px;">${escapeHtml(data.adherence || 'perfect')}</td>
        </tr>
    </table>

    <!-- Risk / Red Flags Section -->
    <h2 style="font-size: 9.5pt; font-weight: bold; text-decoration: underline; margin-top: 10px; margin-bottom: 4px; font-family: 'Arial', sans-serif;">
        Risk/Red Flags:
    </h2>
    <table style="width: 280pt; border-collapse: collapse; margin-bottom: 14px; border: 1px solid #000000; font-size: 8pt; font-family: 'Arial', sans-serif;">
        ${riskRowsHtml}
    </table>

    <!-- Vitals Results Table -->
    <table style="width: 100%; border-collapse: collapse; margin-top: 10px; margin-bottom: 14px; border: 1.5px solid #000000; font-size: 7.5pt; font-family: 'Arial', sans-serif;">
        <tr style="border-bottom: 1.5px solid #000000; height: 18pt;">
            <td style="width: 125pt; border-right: 1px solid #000000; border-bottom: 1px solid #000000;"></td>
            <td style="width: 102pt; padding: 2px 4px; font-weight: bold; border-right: 1px solid #000000; border-bottom: 1px solid #000000; text-align: center;">Initial Result</td>
            <td style="padding: 2px 4px; font-weight: bold; text-align: center; border-bottom: 1px solid #000000;" colspan="3">Last Three Results</td>
        </tr>
        ${vitalsRows}
    </table>

    <!-- Clinical Reminders & AI Pre-Consultation Notes Section -->
    <h2 style="font-size: 9.5pt; font-weight: bold; text-decoration: underline; margin-top: 12px; margin-bottom: 4px; font-family: 'Arial', sans-serif;">
        Clinical Reminders & AI Pre-Consultation Notes:
    </h2>
    <ol style="margin: 0; padding-left: 20px; font-size: 7.5pt; font-family: 'Arial', sans-serif;">
        ${notesHtml}
    </ol>

    <!-- Footer Date & Signature -->
    <div style="margin-top: 24px; font-size: 7.5pt; font-family: 'Arial', sans-serif; font-weight: bold; display: flex; justify-content: space-between; align-items: center;">
        <div>Generated: ${escapeHtml(data.summaryDate)}</div>
        <div>Treating Physician Signature / Stamp ________________________</div>
    </div>
</body>
</html>`;
};

/**
 * Directly downloads the Doctor Clinical Summary PDF
 */
export const openDoctorSummaryPdfWindow = (data: PatientSummaryData = DEFAULT_STATIC_SUMMARY_DATA) => {
  return downloadDoctorSummaryPdfDirect(data);
};

/**
 * Opens Doctor summary template preview in new browser tab
 */
export const openDocGeneratorHtmlWindow = (_data: PatientSummaryData = DEFAULT_STATIC_SUMMARY_DATA) => {
  window.open('/assets/Doctor_Clinical_Summary_00366.html', '_blank');
};

/**
 * Direct PDF Download via Puppeteer Backend Endpoint
 */
export const downloadDoctorSummaryPdfDirect = async (
  data: PatientSummaryData = DEFAULT_STATIC_SUMMARY_DATA
): Promise<void> => {
  const htmlContent = generateSummaryHTMLString(data);
  try {
    const res = await fetch('/api/v1/medikiosk/generate-pdf', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ htmlContent }),
    });

    if (res.ok) {
      const pdfBlob = await res.blob();
      const cleanId = (data.ampathId || '00366').replace(/[^a-zA-Z0-9_-]/g, '_');
      const fileName = `Aethera_Clinical_Summary_${cleanId}.pdf`;
      const url = URL.createObjectURL(pdfBlob);

      const link = document.createElement('a');
      link.href = url;
      link.download = fileName;
      document.body.appendChild(link);
      link.click();

      setTimeout(() => {
        if (document.body.contains(link)) {
          document.body.removeChild(link);
        }
      }, 5000);
      return;
    }
  } catch (err: any) {
    console.warn('Backend PDF generation endpoint error, falling back to browser print:', err);
  }

  // Fallback to client-side window print/PDF download
  const printWin = window.open('', '_blank');
  if (printWin) {
    printWin.document.write(htmlContent);
    printWin.document.close();
    printWin.focus();
    setTimeout(() => {
      printWin.print();
    }, 300);
  } else {
    alert('Pop-up blocked! Please allow pop-ups for PDF generation and printing.');
  }
};

/**
 * Uses Express backend Puppeteer service to download Aethera Clinical Summary PDF directly
 */
export const downloadDoctorSummaryPdfWithPuppeteer = downloadDoctorSummaryPdfDirect;
